apiVersion: v1
kind: Service
metadata:
  name: pedido-service
spec:
  selector:
    app: pedido
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 80
      port: 3001
      nodePort: 30001
