apiVersion: v1
kind: Service
metadata:
  name: pagamento-service
spec:
  selector:
    app: pagamento
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 80
      port: 3002
      nodePort: 30002
